CREATE TABLE report_jobs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owning_user_id BIGINT NOT NULL,
    report_type TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED')),
    request_parameters TEXT NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    failure_reason TEXT,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_report_jobs_owner ON report_jobs(owning_user_id);
CREATE INDEX idx_report_jobs_status_requested ON report_jobs(status, requested_at);

CREATE TABLE completed_reports (
    report_job_id BIGINT PRIMARY KEY,
    pdf_content BYTEA NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'application/pdf',
    stored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_completed_reports_job FOREIGN KEY (report_job_id) REFERENCES report_jobs(id) ON DELETE CASCADE
);
