CREATE TABLE closed_accounting_periods (
    closed_accounting_period_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    transaction_count BIGINT NOT NULL,
    CONSTRAINT uq_closed_accounting_periods_user_range UNIQUE (user_id, start_date, end_date)
);

CREATE INDEX idx_closed_accounting_periods_user_end
    ON closed_accounting_periods(user_id, end_date DESC);

CREATE TABLE archived_journal_entries (
    journal_entry_id BIGINT PRIMARY KEY,
    entry_date DATE NOT NULL,
    description TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL,
    closed_accounting_period_id BIGINT NOT NULL,
    CONSTRAINT fk_archived_journal_entries_period
        FOREIGN KEY (closed_accounting_period_id)
        REFERENCES closed_accounting_periods(closed_accounting_period_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_archived_journal_entries_period
    ON archived_journal_entries(closed_accounting_period_id);

CREATE TABLE archived_journal_lines (
    journal_line_id BIGINT PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    direction CHAR(1) NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    CONSTRAINT fk_archived_journal_lines_entry
        FOREIGN KEY (journal_entry_id)
        REFERENCES archived_journal_entries(journal_entry_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_archived_direction_is_valid
        CHECK (direction IN ('D', 'C')),
    CONSTRAINT chk_archived_amount_is_valid
        CHECK (amount > 0)
);

CREATE INDEX idx_archived_journal_lines_entry_id ON archived_journal_lines(journal_entry_id);
