CREATE TABLE closed_period_account_balances (
    closed_period_account_balance_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    closed_accounting_period_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    balance BIGINT NOT NULL,
    CONSTRAINT fk_closed_period_account_balances_period
        FOREIGN KEY (closed_accounting_period_id)
        REFERENCES closed_accounting_periods(closed_accounting_period_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_closed_period_account_balances_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(account_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_closed_period_account_balances_period_account
        UNIQUE (closed_accounting_period_id, account_id)
);

CREATE INDEX idx_closed_period_account_balances_user_period
    ON closed_period_account_balances(user_id, closed_accounting_period_id);

CREATE INDEX idx_closed_period_account_balances_period
    ON closed_period_account_balances(closed_accounting_period_id);
