CREATE TABLE replayable_journal_entries (
    replayable_journal_entry_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    replay_name TEXT NOT NULL,
    replay_line_count INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_edited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_replayable_journal_entries_user_name UNIQUE (user_id, replay_name),
    CONSTRAINT chk_replayable_journal_entries_line_count CHECK (replay_line_count >= 2)
);

CREATE INDEX idx_replayable_journal_entries_user_id ON replayable_journal_entries(user_id);

CREATE TABLE replayable_journal_entry_lines (
    replayable_journal_entry_line_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    replayable_journal_entry_id BIGINT NOT NULL,
    line_order INT NOT NULL,
    amount BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    direction CHAR(1) NOT NULL,
    CONSTRAINT fk_replayable_journal_entry_lines_entry
        FOREIGN KEY (replayable_journal_entry_id)
        REFERENCES replayable_journal_entries(replayable_journal_entry_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_replayable_journal_entry_lines_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(account_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_replayable_journal_entry_lines_entry_order
        UNIQUE (replayable_journal_entry_id, line_order),
    CONSTRAINT chk_replayable_journal_entry_lines_direction
        CHECK (direction IN ('D', 'C')),
    CONSTRAINT chk_replayable_journal_entry_lines_amount
        CHECK (amount > 0)
);

CREATE INDEX idx_replayable_journal_entry_lines_entry_id
    ON replayable_journal_entry_lines(replayable_journal_entry_id);
