-- account_classifications definition
CREATE TABLE account_classifications (
    classifications_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    classification_description TEXT UNIQUE NOT NULL,
    credit_effect CHAR(1) NOT NULL,
    debit_effect CHAR(1) NOT NULL,
    CONSTRAINT chk_credit_effect_is_valid
        CHECK (credit_effect IN ('+', '-')),
    CONSTRAINT chk_debit_effect_is_valid
        CHECK (debit_effect IN ('+', '-'))
);

-- account_types definition
CREATE TABLE account_types (
    type_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_description TEXT UNIQUE NOT NULL,
    classification_id BIGINT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    type_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_account_types_account_classifications_classification
        FOREIGN KEY (classification_id)
        REFERENCES account_classifications(classifications_id)
        ON DELETE RESTRICT
);

-- chart_of_accounts definition
CREATE TABLE accounts (
    account_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_type_id BIGINT NOT NULL,
    account_description TEXT NOT NULL,
    account_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT NOT NULL DEFAULT '',
    CONSTRAINT fk_accounts_account_types_account_type
        FOREIGN KEY (account_type_id)
        REFERENCES account_types(type_id)
        ON DELETE RESTRICT
);

-- ledger_transactions definition
CREATE TABLE journal_entries (
    journal_entry_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_date DATE NOT NULL,
    description TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT ''
);

-- ledger_transactions definition
CREATE TABLE journal_lines (
    journal_line_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    journal_entry_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    direction CHAR(1) NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    CONSTRAINT fk_journal_lines_accounts_account_id
        FOREIGN KEY (account_id)
        REFERENCES accounts(account_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_journal_lines_journal_entries_journal_entry_id
        FOREIGN KEY (journal_entry_id)
        REFERENCES journal_entries(journal_entry_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_direction_is_valid
        CHECK (direction IN ('D', 'C')),
    CONSTRAINT chk_amount_is_valid
        CHECK (amount > 0)
);

CREATE INDEX idx_account_types_classification_id ON account_types(classification_id);
CREATE INDEX idx_accounts_account_type ON accounts(account_type_id);
CREATE INDEX idx_journal_lines_entry_id ON journal_lines(journal_entry_id);
CREATE INDEX idx_journal_lines_account_id ON journal_lines(account_id);