-- pending_transactions definition
CREATE TABLE pending_transactions (
    transaction_number BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    description TEXT NOT NULL,
    amount BIGINT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    CONSTRAINT chk_pending_transactions_amount_is_valid
        CHECK (amount > 0)
);

CREATE INDEX idx_pending_transactions_user_id ON pending_transactions(user_id);

-- import_formats definition
CREATE TABLE import_formats (
    format_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    format_name TEXT NOT NULL,
    format_type TEXT NOT NULL,
    format_details JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    bean_name TEXT NOT NULL,
    CONSTRAINT uq_import_formats_name_type UNIQUE (format_name, format_type),
    CONSTRAINT uq_import_formats_bean_name UNIQUE (bean_name)
);

-- Seed initial import format: USAA Bank (.csv)
INSERT INTO ledger.import_formats(format_id, format_name, format_type, format_details, active, bean_name)
VALUES (
    1,
    'USAA Bank',
    '.csv',
    '{
      "dateFormat": "MM/dd/yyyy",
      "headerArray": ["Date","Description","Original Description","Category","Amount","Status"]
    }'::jsonb,
    true,
    'USAABankDefault'
);

