-- Budget planning: master plan and child tables (30/365 frequency math applied in application layer)

CREATE TABLE budgeting_plans (
    budget_plan_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_edited_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_budgeting_plans_user_id ON budgeting_plans(user_id);

CREATE TABLE bp_incomes (
    bp_income_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    budget_plan_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL,
    frequency_unit TEXT NOT NULL,
    frequency_number INT NOT NULL,
    account_id BIGINT NOT NULL,
    CONSTRAINT fk_bp_incomes_plan FOREIGN KEY (budget_plan_id)
        REFERENCES budgeting_plans(budget_plan_id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_incomes_account FOREIGN KEY (account_id)
        REFERENCES accounts(account_id) ON DELETE RESTRICT,
    CONSTRAINT chk_bp_incomes_frequency_unit
        CHECK (frequency_unit IN ('days', 'weeks', 'months', 'years')),
    CONSTRAINT chk_bp_incomes_frequency_number CHECK (frequency_number > 0),
    CONSTRAINT chk_bp_incomes_amount_minor CHECK (amount_minor <> 0)
);

CREATE INDEX idx_bp_incomes_plan_id ON bp_incomes(budget_plan_id);

CREATE TABLE bp_recurring_payables (
    bp_recurring_payable_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    budget_plan_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    amount_minor BIGINT NOT NULL,
    frequency_unit TEXT NOT NULL,
    frequency_number INT NOT NULL,
    budget_account_id BIGINT NOT NULL,
    CONSTRAINT fk_bp_recurring_payables_plan FOREIGN KEY (budget_plan_id)
        REFERENCES budgeting_plans(budget_plan_id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_recurring_payables_budget_account FOREIGN KEY (budget_account_id)
        REFERENCES accounts(account_id) ON DELETE RESTRICT,
    CONSTRAINT chk_bp_recurring_payables_frequency_unit
        CHECK (frequency_unit IN ('days', 'weeks', 'months', 'years')),
    CONSTRAINT chk_bp_recurring_payables_frequency_number CHECK (frequency_number > 0),
    CONSTRAINT chk_bp_recurring_payables_amount_minor CHECK (amount_minor <> 0)
);

CREATE INDEX idx_bp_recurring_payables_plan_id ON bp_recurring_payables(budget_plan_id);

CREATE TABLE bp_budgets (
    bp_budget_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    budget_plan_id BIGINT NOT NULL,
    target_amount_per_day_minor BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    CONSTRAINT fk_bp_budgets_plan FOREIGN KEY (budget_plan_id)
        REFERENCES budgeting_plans(budget_plan_id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_budgets_account FOREIGN KEY (account_id)
        REFERENCES accounts(account_id) ON DELETE RESTRICT,
    CONSTRAINT chk_bp_budgets_target_nonzero CHECK (target_amount_per_day_minor <> 0)
);

CREATE INDEX idx_bp_budgets_plan_id ON bp_budgets(budget_plan_id);

CREATE TABLE bp_funding_lines (
    bp_funding_line_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bp_budget_id BIGINT NOT NULL,
    bp_income_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL,
    frequency_unit TEXT NOT NULL,
    frequency_number INT NOT NULL,
    CONSTRAINT fk_bp_funding_lines_budget FOREIGN KEY (bp_budget_id)
        REFERENCES bp_budgets(bp_budget_id) ON DELETE CASCADE,
    CONSTRAINT fk_bp_funding_lines_income FOREIGN KEY (bp_income_id)
        REFERENCES bp_incomes(bp_income_id) ON DELETE RESTRICT,
    CONSTRAINT chk_bp_funding_lines_frequency_unit
        CHECK (frequency_unit IN ('days', 'weeks', 'months', 'years')),
    CONSTRAINT chk_bp_funding_lines_frequency_number CHECK (frequency_number > 0),
    CONSTRAINT chk_bp_funding_lines_amount_minor CHECK (amount_minor <> 0)
);

CREATE INDEX idx_bp_funding_lines_budget_id ON bp_funding_lines(bp_budget_id);
CREATE INDEX idx_bp_funding_lines_income_id ON bp_funding_lines(bp_income_id);
