-- users definition
CREATE TABLE users (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_date TIMESTAMP NOT NULL,
    updated_date TIMESTAMP
);

-- users definition
CREATE TABLE user_sessions (
    session_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    session_token TEXT UNIQUE NOT NULL,
    created_date TIMESTAMP NOT NULL,
    expires_date TIMESTAMP Not NULL,
    CONSTRAINT fk_current_user_sessions_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);

CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_date);