CREATE TABLE service_permissions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_name TEXT UNIQUE NOT NULL,
    secret_hash TEXT NOT NULL,
    allowed_audiences TEXT NOT NULL,
    allowed_scopes TEXT NOT NULL,
    may_act_for_user BOOLEAN NOT NULL DEFAULT FALSE,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_service_permissions_service_name ON service_permissions(service_name);

INSERT INTO service_permissions (service_name, secret_hash, allowed_audiences, allowed_scopes, may_act_for_user)
VALUES (
    'reporting-service',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    'ledger-service',
    'ledger.accounts.read,ledger.journalentries.read',
    TRUE
);
