CREATE TABLE user_settings (
    setting_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    setting_name TEXT NOT NULL,
    setting_value TEXT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_date TIMESTAMP,
    CONSTRAINT fk_user_settings_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_user_settings_user_name UNIQUE (user_id, setting_name)
);

CREATE INDEX idx_user_settings_user_id ON user_settings(user_id);
