CREATE TABLE notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_system TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    seen BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unseen ON notifications(user_id) WHERE seen = FALSE;
