CREATE TABLE user_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    role_name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_roles_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT uq_user_roles_user_role UNIQUE (user_id, role_name)
);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);

CREATE TABLE user_feedback (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    seen BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user_feedback_users_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);

CREATE INDEX idx_user_feedback_type_created ON user_feedback(type, created_at DESC);
CREATE INDEX idx_user_feedback_user_id ON user_feedback(user_id);
